### PR TITLE
Issue #57 resolved, multiplication underflow

### PR DESCRIPTION
**Pull request by manili**

### CODE REVIEW

**Comment by manili** [comment]
Sorry about that.
I use the "New pull request" button on top of [your repository](https://github.com/jbush001/NyuziProcessor). I can not understand why Github also include my previous changes.

**Comment by jbush001** [comment]
I think you need to integrate changes from my repository into your fork. This is an important thing to know how to do. There are instructions here: https://help.github.com/articles/syncing-a-fork/

But I'll summarize:

Do this only once:

`$ git remote add upstream https://github.com/jbush001/NyuziProcessor`

Do this any time you want to sync your branch:

```
$ git fetch upstream
$ git merge upstream/master
```

Once you've done this, you should be able to create a new pull request.

**Comment by manili** [comment]
sorry for the newbie's mistakes. It looks like that everything's OK, because now GitHub tell me we have identical master branches.  I'll do my best next time. Would you mind cancel my pull request, please?

**Comment by jbush001** [comment]
No need to apologize, you're doing this for the first time and that's how you learn. Unfortunately, some of this stuff is not very obvious.

**Pull request closed without merging**
